include: package:flutter_lints/flutter.yaml

linter:
  rules:
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_print: true
    avoid_slow_async_io: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true