name: 🔨 Build & Release NetManager .APK

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: 📁 Checkout
        uses: actions/checkout@v4

      - name: 📋 Cache
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: ${{ runner.os }}-pub-

      - name: ☕️ Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: 🦋 Setup Flutter
        uses: subosito/flutter-action@v2.22.0
        with:
          channel: stable

      - name: ✔️ Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: 🪛 Dependencies
        run: flutter pub get

      - name: ✅ Tests
        run: flutter test --coverage

      - name: 🔓 Key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" > $GITHUB_WORKSPACE/android/key.properties

      - name: 🗄️ Upload-keystore.jks
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/android/upload-keystore.jks

      - name: 📝 Define GIT_COMMIT
        run: echo "GIT_COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: ⛏️ APKs
        run: flutter build apk --release --dart-define=SENTRY_DSN=${{ secrets.SENTRY_DSN }} --dart-define=flutter.flutter_map.unblockOSM=${{ secrets.UNBLOCK_OSM }} --dart-define=GIT_COMMIT=$GIT_COMMIT --target-platform android-arm,android-arm64

      - name: 📦 Artifacts
        run: |
          mkdir -p artifacts
          cp build/app/outputs/flutter-apk/*.apk artifacts/
          cp build/wear/outputs/apk/release/*.apk artifacts/

      - name: 📤 Upload
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        uses: actions/upload-artifact@v4
        with:
          path: artifacts/*.apk
          retention-days: 3

      - name: 🏷️ Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: ncipollo/release-action@v1.16.0
        with:
          tag:       ${{ github.ref_name }}
          name:      Release ${{ github.ref_name }}
          artifacts: artifacts/*.apk
          token:     ${{ secrets.GITHUB_TOKEN }}